# Generated by Django 5.1.5 on 2025-02-25 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='specialized',
            field=models.CharField(blank=True, choices=[('Specialist', 'Specialist'), ('Medical Officer', 'MO'), ('Consultant', 'Consultant')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='recent_labs',
            field=models.ImageField(blank=True, null=True, upload_to='lab_images/'),
        ),
        migrations.CreateModel(
            name='DoctorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_id', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('place_of_work', models.CharField(max_length=255)),
                ('payment_options', models.CharField(choices=[('Mobile Money', 'Mobile Money'), ('Bank Transfer', 'Bank Transfer'), ('Paypal', 'Paypal')], max_length=50)),
                ('payment_name', models.CharField(help_text='Registered name on the preferred payment method', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.CharField(blank=True, max_length=255, null=True)),
                ('allergies_detail', models.TextField(blank=True, null=True)),
                ('chronic_disease_status', models.CharField(blank=True, max_length=50, null=True)),
                ('chronic_disease_detail', models.TextField(blank=True, null=True)),
                ('smoking_status', models.CharField(blank=True, max_length=50, null=True)),
                ('smoking_detail', models.TextField(blank=True, null=True)),
                ('alcohol_status', models.CharField(blank=True, max_length=50, null=True)),
                ('alcohol_detail', models.TextField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('genotype', models.CharField(blank=True, max_length=10, null=True)),
                ('implant', models.TextField(blank=True, null=True)),
                ('vitals', models.TextField(blank=True, null=True)),
                ('prostate_screening', models.CharField(blank=True, max_length=10, null=True)),
                ('cervical_cancer_screening', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PharmacistHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_id', models.CharField(max_length=255, unique=True)),
                ('address_of_pharmacy', models.CharField(max_length=255)),
                ('place_of_work', models.CharField(max_length=255)),
                ('payment_options', models.CharField(choices=[('Mobile Money', 'Mobile Money'), ('Bank Transfer', 'Bank Transfer'), ('Paypal', 'Paypal')], max_length=50)),
                ('payment_name', models.CharField(help_text='Registered name on the preferred payment method', max_length=255)),
                ('delivery_options', models.CharField(choices=[('Pick up only', 'Pick up only'), ('Delivery available', 'Delivery available')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacist_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
