# Generated by Django 5.1.5 on 2025-02-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorhistory',
            name='payment_options',
            field=models.CharField(choices=[('mobile money', 'Mobile Money'), ('bank transfer', 'Bank Transfer'), ('paypal', 'Paypal')], max_length=50),
        ),
    ]
