# Generated by Django 5.1.5 on 2025-02-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_doctorhistory_payment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacisthistory',
            name='payment_options',
            field=models.CharField(choices=[('mobile money', 'Mobile Money'), ('bank transfer', 'Bank Transfer'), ('paypal', 'Paypal')], max_length=50),
        ),
    ]
