# Generated by Django 5.1.5 on 2025-02-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_pharmacisthistory_payment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthistory',
            name='breast_cancer_screening',
            field=models.CharField(default='No', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='gender',
            field=models.CharField(default='F', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='alcohol_status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='blood_group',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='cervical_cancer_screening',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='genotype',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='prostate_screening',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='smoking_status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
