# Generated by Django 5.1.5 on 2025-02-06 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('history', models.TextField()),
                ('examination_findings', models.TextField(blank=True)),
                ('treatment_plan', models.TextField()),
                ('prescriptions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('awaiting_review', 'Awaiting review')], default='awaiting_review', max_length=50)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='appointments.appointment')),
            ],
        ),
    ]
