# Generated by Django 5.1.5 on 2025-02-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='investigations',
            field=models.TextField(blank=True),
        ),
    ]
