# Generated by Django 5.1.5 on 2025-02-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_consultation_investigations'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='prescription_served',
            field=models.BooleanField(default=False),
        ),
    ]
